export const promotionsData = [
    {
        app_erid: "2W5zFGtQVXX",
        description: "Активируйте бонусную карту и получите 10 000 приветственных бонусов на счет",
        entry_point: "june_26",
        erid: "2W5zFGtQVXX",
        filter: "По направлениям",
        ligal: 'Реклама. ООО "Санмар Тур"',
        name: "SunmarBonus «Мы вам рады!»",
        promo_end: "2026-12-31T23:59:59Z",
        promo_end_text: "1 бонус = 1 рубль",
        url: "#",
        visual: "/SunmarBonus.svg"
    },
    {
        app_erid: "2W5zFGtQVXX",
        description: "Отдых по очень выгодным ценам!",
        entry_point: "june_26",
        erid: "2W5zFGtQVXX",
        filter: "По направлениям",
        ligal: 'Реклама. ООО "Санмар Тур"',
        name: "Sunmar ФОРТУНА",
        promo_end: "2026-12-31T23:59:59Z",
        promo_end_text: "",
        url: "#",
        visual: "/SunmarFortune.svg"
    },
    {
        app_erid: "2W5zFGtQVXX",
        description: "Для туристов, которые хотят улететь в ближайшее время",
        entry_point: "june_26",
        erid: "2W5zFGtQVXX",
        filter: "По направлениям",
        ligal: 'Реклама. ООО "Санмар Тур"',
        name: "Турция. Горящие предложения",
        promo_end: "2026-12-31T23:59:59Z",
        promo_end_text: "",
        url: "#",
        visual: "/SunmarTurkey.svg"
    },
    {
        app_erid: "2W5zFGtQVXX",
        description: "Отели России с бесплатным проживанием для детей",
        entry_point: "june_26",
        erid: "2W5zFGtQVXX",
        filter: "По направлениям",
        ligal: 'Реклама. ООО "Санмар Тур"',
        name: "Акция Бесплатный отдых для детей",
        promo_end: "2026-12-31T23:59:59Z",
        promo_end_text: "",
        url: "#",
        visual: "/SunmarChildren.svg"
    },
    {
        app_erid: "2W5zFGtQVXX",
        description: "Подборка премиальных отелей в Турции",
        entry_point: "june_26",
        erid: "2W5zFGtQVXX",
        filter: "По направлениям",
        ligal: 'Реклама. ООО "Санмар Тур"',
        name: "Не ищите способы сэкономить на роскоши, мы уже подумали за вас",
        promo_end: "2026-12-31T23:59:59Z",
        promo_end_text: "",
        url: "#",
        visual: "/SunmarEconomical.svg"
    },
    {
        app_erid: "2W5zFGtQVXX",
        description: "",
        entry_point: "june_26",
        erid: "2W5zFGtQVXX",
        filter: "По направлениям",
        ligal: 'Реклама. ООО "Санмар Тур"',
        name: "Пакеты услуг в отелях ОАЭ",
        promo_end: "2026-12-31T23:59:59Z",
        promo_end_text: "",
        url: "#",
        visual: "/SunmarServicePackages.svg"
    }
];